### ISSUE TITLE
Add a way to implement restart after setting config

### ISSUE THREAD

**Issue by gabriel-cardoso** [glyph-fr/capistrano-dotenv-tasks#10]
Could be nice to have a way to implement/override a callback to force server restart after config update.

In my case, I need to `cap unicorn:stop` and `cap unicorn:start` after using `cap config:set` command.

**Comment by vala** [comment]
This can be achieved by adding a hook in your capistrano `deploy.rb` with something like this :

```ruby
after "config:set", "unicorn:restart"
```

Closing as it can be achieved easily using capistrano basic API.
