### ISSUE TITLE
Quoted values get unquoted when a separate value is added and sorted

### ISSUE THREAD

**Issue by heironimus** [glyph-fr/capistrano-dotenv-tasks#12]
Some values require quotes, particularly if they are long or have special characters in them. These quotes are removed when a new, different key is added. https://github.com/glyph-fr/capistrano-dotenv-tasks/blob/master/lib/capistrano/dotenv/config.rb#L20

**Comment by vala** [comment]
Hi there, can you please provide some examples of values that do not work without quotes ?
What approach would you recommend to cover all the cases ?

If this seems easy enough to solve for your, a PR would be much appreciated !

**Comment by heironimus** [comment]
Example
```
PASSWORD="abc#123"
```
If the quotes are removed, the value is read as `abc`

I'll see if I can get a PR together.

**Comment by heironimus** [comment]
PR #13

**Comment by heironimus** [comment]
BTW, super-handy gem. Thanks!

**Comment by vala** [comment]
Thanks for your PR !
