### ISSUE TITLE
Add git tags to repository

### ISSUE THREAD

**Issue by koenpunt** [glyph-fr/capistrano-dotenv-tasks#9]
It is common practice to add the released versions as tags to git repository. This also makes it easier to see if the latest features in the source are released or not.

**Comment by vala** [comment]
Yes, actually there's no workflow for this the gem's release process. I'll add those tags from now on and push a tag for the current version next week, and release the latest updates.

**Comment by vala** [comment]
Sorry for the delay, but I had SSL issues with rubygems lately and missed time. I just pushed the 0.1.4 tag and released this version to rubygems. Again, thanks for the workflow tip, I should use this method on the other repos I maintain too.
